[package]
name = "ownlinkmemo_infra_file"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
ownlinkmemo_domain = { path = "../domain"}
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4"
