[package]
name = "ownlinkmemo_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ownlinkmemo_domain = { path = "../../domain" }
egui = "0.18.1"
chrono = { version = "0.4" , features = ["serde"]}