[package]
name = "ownlinkmemo_cli_file"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
ownlinkmemo_domain = { path = "../domain"}
ownlinkmemo_infra_file = { path = "../infra_file"}
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4"
clap = "3.1.6"
